package com.system.mapper;

import com.system.po.Selectedcourse;
import com.system.po.SelectedcourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectedcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    int countByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    int deleteByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    int insert(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    int insertSelective(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    List<Selectedcourse> selectByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);
}