spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url : jdbc:mysql://localhost:3306/hsweb3?characterEncoding=utf8&useUnicode=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
        username : root
        password : root
logging:
  level:
    access-logger: INFO
hsweb:
  authorize:
    auto-parse: true
    sync: true

swagger:
  title: hsweb 3.0 api
  description: hsweb 企业后台管理基础框架
  version: 3.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: http://www.hsweb.me/
  contact:
    name: zhouhao
    url: https://github.com/zhou-hao
    email: i@hsweb.me
  base-package: org.hswebframework.web