package com.system.po;

import java.io.Serializable;

public class College implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeID
     *
     * @mbggenerated
     */
    private Integer collegeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeName
     *
     * @mbggenerated
     */
    private String collegename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table college
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.collegeID
     *
     * @return the value of college.collegeID
     *
     * @mbggenerated
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.collegeID
     *
     * @param collegeid the value for college.collegeID
     *
     * @mbggenerated
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.collegeName
     *
     * @return the value of college.collegeName
     *
     * @mbggenerated
     */
    public String getCollegename() {
        return collegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.collegeName
     *
     * @param collegename the value for college.collegeName
     *
     * @mbggenerated
     */
    public void setCollegename(String collegename) {
        this.collegename = collegename == null ? null : collegename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        College other = (College) that;
        return (this.getCollegeid() == null ? other.getCollegeid() == null : this.getCollegeid().equals(other.getCollegeid()))
            && (this.getCollegename() == null ? other.getCollegename() == null : this.getCollegename().equals(other.getCollegename()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCollegeid() == null) ? 0 : getCollegeid().hashCode());
        result = prime * result + ((getCollegename() == null) ? 0 : getCollegename().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collegeid=").append(collegeid);
        sb.append(", collegename=").append(collegename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}